---
- name: Jetstack Helm repo present
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Cert-Manager deployed
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    create_namespace: true
    chart_version: "1.12.1"
    values:
      installCRDs: "true"
      extraArgs:
        - "--dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53"
        - "--dns01-recursive-nameservers-only"
      podDnsPolicy: None
      podDnsConfig:
        nameservers:
          - "1.1.1.1"
          - "9.9.9.9"
    update_repo_cache: true
  run_once: true

- name: Cloudflare API secret present
  kubernetes.core.k8s:
    definition:
      kind: Secret
      metadata:
        name: cloudflare-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        cloudflare-token: "{{ lookup('hashi_vault', 'secret=kv/data/cloudflare-rpt:CF_DNS_API_TOKEN') }}"
  run_once: true

- name: LetsEncrypt ClusterIssuer present
  kubernetes.core.k8s:
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-production
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: "{{ lookup('hashi_vault', 'secret=kv/data/cloudflare-rpt:info_address') }}"
          privateKeySecretRef:
            name: letsencrypt-production
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-token-secret
                    key: cloudflare-token
              selector:
                dnsZones:
                  - "{{ lookup('hashi_vault', 'secret=kv/data/cloudflare-rpt:dns_zone') }}"
  run_once: true
