---
- name: Jetstack Helm repo present
  kubernetes.core.helm_repository:
      name: jetstack
      repo_url: https://charts.jetstack.io

- name: Cert-Manager deployed
  kubernetes.core.helm:
    name: cert-manager
    namespace: cert-manager
    chart_ref: jetstack/cert-manager
    create_namespace: true
    chart_version: "1.12.1"
    values:
      installCRDs: "true"
    update_repo_cache: true
  run_once: true