---
- name: Hashicorp repo present
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: Vault namespace present
  kubernetes.core.k8s:
    kind: Namespace
    name: vault
  run_once: true

- name: Vault deployed
  kubernetes.core.helm:
    name: vault
    namespace: vault
    chart_ref: hashicorp/vault
    update_repo_cache: true
    values:
      injector:
        enabled: true
        image:
          tag: "latest"
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 250m
      server:
        enabled: true
        image:
          tag: "1.14.0"
        resources:
          requests:
            memory: 4Gi
            cpu: 1000m
          limits:
            memory: 8Gi
            cpu: 1000m
        readinessProbe:
          enabled: true
          path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
        livenessProbe:
          enabled: true
          path: "/v1/sys/health?standbyok=true"
          initialDelaySeconds: 60
        dataStorage:
          storageClass: "longhorn"
      ui:
        enabled: true
        serviceType: "LoadBalancer"
  run_once: true 
