---

- hosts: all
  become: true
  roles:
    - role: prereq
      tags: k3s

- hosts: master
  become: true
  roles:
    - role: k3s/master
      tags: k3s

- hosts: node
  become: true
  roles:
    - role: k3s/node
      tags: k3s

- hosts: master
  become: true
  roles:
    - role: k3s/post
      tags: k3s
    - role: cert-manager
      tags: cert-manager
    - role: rancher
      tags: rancher
    - role: vault
      tags: vault
    - role: traefik
      tags: traefik
